// Code generated by "stringer -type=Status -linecomment"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnknown-0]
	_ = x[StatusEnded-1]
	_ = x[StatusReading-2]
	_ = x[StatusDrop-3]
	_ = x[StatusOnHold-4]
}

const _Status_name = "unknownendedreadingdroponHold"

var _Status_index = [...]uint8{0, 7, 12, 19, 23, 29}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
